### ISSUE TITLE
Hubitat - MissingMethodException

### ISSUE THREAD

**Issue by Tommyboy51300** [SANdood/PurpleAirStation#1]
First and foremost, thanks for all of your work!

I'm converting over from Smartthings to Hubitat and unable to get PurpleAir driver to work. New .14 version states a metadata error due to missing metadata capability "Air Quality Sensor" that was recently added to the code. Try to go back to .13 version and get missing method exception. This is after making the hubitat code modification in 2 places. Any thoughts or pointers would be appreciated. Exception below:

dev:2072019-03-26 04:19:07.295 pm errorgroovy.lang.MissingMethodException: No signature of method: user_driver_sandood_PurpleAir_Air_Quality_Station_322.asynchttpget() is applicable for argument types: (java.lang.String, java.util.LinkedHashMap) values: [purpleAirResponse, [uri:https://www.purpleair.com, path:/json, ...]] on line 259 (getPurpleAirAQI)

**Comment by SANdood** [comment]
Just comment out the line that says “capability Air Quality Sensor”

Thanks!
      Barry

**Comment by Tommyboy51300** [comment]
I had already tried that before reverting to the .13 version. I tried again, I still get the following exception in the logs.

2019-03-26 09:09:43.616 pm errorgroovy.lang.MissingMethodException: No signature of method: user_driver_sandood_PurpleAir_Air_Quality_Station_327.asynchttpget() is applicable for argument types: (java.lang.String, java.util.LinkedHashMap) values: [purpleAirResponse, [uri:https://www.purpleair.com, path:/json, ...]] on line 266 (refresh)

**Comment by SANdood** [comment]
Updated version 1.1.01 now auto-supports deployment on both SmartThings and Hubitat

**Comment by Tommyboy51300** [comment]
Confirmed. Thank you!
